### ISSUE TITLE
Unable to run cellery run within Ballerina Project

### ISSUE THREAD

**Issue by azinneera** [wso2/cellery#952]
**Description:**
`cellery run` command cannot be executed within a ballerina project. This is because the way we are trying to distinguish between a single file and a ballerina project [1] to run the `ballerina run` command. 

IMO, We should revisit the end-to-end flow of the way we treat a ballerina project and implement changes in the init, build, run and test commands accordingly.

[1] https://github.com/wso2-cellery/sdk/blob/master/components/module-cellery/cellery-utils/src/main/java/io/cellery/impl/CreateInstance.java#L701

**Comment by nadundesilva** [comment]
@azinneera This is not necessarily due to the way we pack the Ballerina project, is it?

I believe if you want to use the working directory to detect the Ballerina project [1], you need to change the working directory when the new process is spawned by the CLI to execute `ballerina run`.

This is not currently done in the Bal Executor [2] . we need to set `cmd.Dir` [3] to the relevant working directory (The temporary directory in which this is being done).

However on a different note, we do need to revisit the build story and the way we pack the project and we can probably make the changes as and when we revamp it. However we need to **set the proper working directory** if we are using it as well.

[1] https://github.com/wso2-cellery/sdk/blob/master/components/module-cellery/cellery-utils/src/main/java/io/cellery/impl/CreateInstance.java#L701
[2] https://github.com/wso2-cellery/sdk/blob/master/components/cli/pkg/ballerina/bal_executor.go#L97
[3] https://golang.org/pkg/os/exec/#Cmd

**Comment by azinneera** [comment]
@nadundesilva Yes it not because of the way we package the project in to the image, rather the execution is done in the pwd. 

Yes, setting the `cmd.Dir` will resolve the issue but I too prefer revisiting the build story for ballerina projects which will resolve most of the known issues of this release.

**Comment by nadundesilva** [comment]
I think we anyway have to set `cmd.Dir` whether or not we change the way we build since we rely on current working directory inside Ballerina. This need to be done consistently in the Bal Executor for all methods.

**Comment by azinneera** [comment]
Resolved
